# Generated by Django 2.0.4 on 2018-05-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='gtime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
